name: Manual MATCHES Update

on:
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install dependencies
      run: npm install # or yarn install

    - name: Run the script
      run: node app/api/cron/manualGames.mjs
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
